### ISSUE TITLE
Original Musicgen or Finetuned

### ISSUE THREAD

**Issue by C00reNUT** [kennethnym/infinifi#13]
Hello,
this is a nice little demo, may I ask are you using finetuned version of musicgen model or the original FB version? 

And what model size are you using to serve the requests?

The consistency is very nice! Thank you.

**Comment by kennethnym** [comment]
im using musicgen large from meta, im working on finetuning musicgen small but the results so far have been disappointing. also glad u like the website!

**Comment by kennethnym** [comment]
yeah, a 3090 worked well in my experience.
