### ISSUE TITLE
Can play/pause button audio also respect the current volume?

### ISSUE THREAD

**Issue by manu-chroma** [kennethnym/infinifi#5]
As mentioned in the title. It's a bit jarring to hear play/pause button audio being super loud in case you're listening to music at much lower volume toggled via the website UI. 

Great product btw!

**Comment by kennethnym** [comment]
good point, didn't think about it, i will get this fixed!

**Comment by kennethnym** [comment]
fixed in https://github.com/kennethnym/infinifi/commit/6ba045fddbac1896107e96e41036af4636cc7eb0

**Comment by manu-chroma** [comment]
Thank you!
